### POST request to create User
POST http://localhost:4000/users
Content-Type: application/json

{
  "firstName": "Tran Tuan",
  "lastName": "Thang",
  "email": "thag@vip.com",
  "password": "Password123!",
  "role": "STUDENT",
  "gender": true,
  "dob": "1990-05-15",
  "created_date": "1990-08-11"
}
###