INSERT INTO QUIZ (NAME, DESCRIPTION)
VALUES ('Java Basics', 'Quiz kiểm tra kiến thức cơ bản về Java'),
       ('Spring Boot', 'Quiz về Spring Boot, Annotation, và cấu hình'),
       ('Database SQL', 'Quiz về câu lệnh SQL và các phép JOIN'),
       ('HTML & CSS', 'Quiz kiểm tra kiến thức web cơ bản'),
       ('JavaScript', 'Quiz về cú pháp và logic JavaScript');

INSERT INTO users (first_name, last_name, email, password, role, gender, dob, created_date)
VALUES ('Nguyễn Văn', 'A', 'nguyenvana@example.com', '$2a$10$xJwL5v5Jz5U6XU5XU5XU5e', 'ADMIN', 1, '1990-05-15',
        '2023-01-10'),
       ('Trần Thị', 'B', 'tranthib@example.com', '$2a$10$xJwL5v5Jz5U6XU5XU5XU5e', 'STUDENT', 0, '2000-08-20',
        '2023-02-15'),
       ('Lê Văn', 'C', 'levanc@example.com', '$2a$10$xJwL5v5Jz5U6XU5XU5XU5e', 'STUDENT', 1, '2002-03-10', '2023-03-20'),
       ('Phạm Thị', 'D', 'phamthid@example.com', '$2a$10$xJwL5v5Jz5U6XU5XU5XU5e', 'STUDENT', 0, '2001-11-25',
        '2023-04-25'),
       ('Hoàng Văn', 'E', 'hoangvane@example.com', '$2a$10$xJwL5v5Jz5U6XU5XU5XU5e', 'ADMIN', 1, '1985-07-30',
        '2023-05-30');

INSERT INTO trait (code, name_vie, name_en, description)
VALUES ('R', 'Thực tế', 'Realistic',
        'Nhóm Realistic bao gồm những người yêu thích làm việc với đôi tay, sử dụng công cụ, máy móc hoặc hoạt động ngoài trời. Họ có tính cách thực tế, thực dụng, tập trung vào các nhiệm vụ cụ thể và có kết quả hữu hình. Những người thuộc nhóm này thường giỏi trong các hoạt động thể chất, có kỹ năng thực hành tốt và thích giải quyết các vấn đề thực tế hơn là làm việc với lý thuyết trừu tượng hay giao tiếp xã hội phức tạp. Họ đáng tin cậy, thẳng thắn, kiên nhẫn và thường không thoải mái trong các môi trường đòi hỏi sự sáng tạo nghệ thuật hoặc tương tác xã hội sâu sắc. Môi trường làm việc lý tưởng cho nhóm Realistic là những nơi như xưởng sản xuất, công trường, trang trại hoặc bất kỳ không gian nào cho phép họ vận động và tạo ra kết quả vật chất.'),
       ('I', 'Nghiên cứu', 'Investigative',
        'Những người thuộc nhóm Investigative có niềm đam mê tìm tòi, khám phá và phân tích để giải quyết các vấn đề phức tạp. Họ tò mò, logic và độc lập, thường bị thu hút bởi khoa học, công nghệ hoặc các ý tưởng trừu tượng. Với tư duy phân tích sắc bén, họ thích làm việc với dữ liệu, nghiên cứu và suy nghĩ sâu sắc hơn là tham gia vào các hoạt động xã hội hay thể chất. Người Investigative thường khách quan, ít bị chi phối bởi cảm xúc và thích làm việc độc lập thay vì phụ thuộc vào nhóm. Môi trường làm việc phù hợp với họ là các phòng thí nghiệm, trung tâm nghiên cứu hoặc bất kỳ nơi nào khuyến khích tư duy logic, sự đổi mới và khám phá tri thức.'),
       ('A', 'Nghệ thuật', 'Artistic',
        'Nhóm Artistic bao gồm những cá nhân yêu thích sự sáng tạo và thể hiện bản thân thông qua nghệ thuật, âm nhạc, văn học hoặc các hình thức sáng tác khác. Họ có trí tưởng tượng phong phú, cảm xúc sâu sắc và gu thẩm mỹ cao, luôn tìm kiếm cái đẹp và sự độc đáo. Người thuộc nhóm này thường nhạy cảm, độc lập và không thích bị gò bó bởi các quy tắc hay cấu trúc cứng nhắc. Họ thích làm việc trong môi trường tự do, nơi họ có thể tự do thể hiện ý tưởng và cảm xúc của mình. Các studio, nhà hát, công ty sáng tạo nội dung hoặc bất kỳ không gian nào khuyến khích sự đổi mới nghệ thuật đều là môi trường lý tưởng cho nhóm Artistic.'),
       ('S', 'Xã hội', 'Social',
        'Những người thuộc nhóm Social có niềm đam mê giúp đỡ và hỗ trợ người khác, tập trung vào việc tạo ra sự thay đổi tích cực trong cộng đồng. Họ thân thiện, đồng cảm, kiên nhẫn và có kỹ năng giao tiếp, lắng nghe xuất sắc. Người Social thích làm việc nhóm, quan tâm đến phúc lợi của người khác và thường có trách nhiệm xã hội cao. Họ cảm thấy thoải mái trong các tình huống đòi hỏi sự tương tác và hỗ trợ lẫn nhau, đồng thời tránh các công việc quá kỹ thuật hoặc đơn lẻ. Môi trường làm việc phù hợp với họ là trường học, bệnh viện, tổ chức phi chính phủ hoặc các trung tâm cộng đồng, nơi họ có thể xây dựng mối quan hệ và giúp đỡ người khác.'),
       ('E', 'Quản lý', 'Enterprising',
        'Nhóm Enterprising bao gồm những người năng động, tham vọng và có khả năng lãnh đạo, thích thuyết phục và quản lý người khác để đạt được mục tiêu. Họ tự tin, tràn đầy năng lượng, giỏi giao tiếp và đàm phán, đồng thời có tầm nhìn chiến lược và khả năng tổ chức tốt. Người Enterprising thường thích cạnh tranh, mạo hiểm và không ngại đối mặt với thách thức để đạt được thành công. Họ phát triển mạnh trong các môi trường đòi hỏi sự ra quyết định nhanh chóng và ảnh hưởng đến người khác. Các công ty, tổ chức kinh doanh, hoặc môi trường chính trị cạnh tranh cao là nơi lý tưởng cho nhóm này.'),
       ('C', 'Nguyên tắc', 'Conventional',
        'Những người thuộc nhóm Conventional yêu thích làm việc với dữ liệu, quy trình và hệ thống, có tính cách kỷ luật, cẩn thận và chú trọng đến chi tiết. Họ thích trật tự, quy tắc và các công việc có cấu trúc rõ ràng, nơi họ có thể tổ chức và quản lý thông tin một cách hiệu quả. Người Conventional thường đáng tin cậy, hiệu quả và không thích các môi trường sáng tạo hoặc không ổn định. Họ giỏi làm việc với số liệu, tài liệu hoặc các hệ thống có tổ chức, và cảm thấy thoải mái khi mọi thứ được sắp xếp ngăn nắp. Văn phòng, ngân hàng, công ty tài chính hoặc các tổ chức có cấu trúc là môi trường làm việc lý tưởng cho nhóm này.');

INSERT INTO question (quiz_id, content)
VALUES (1, 'Bạn có thích kiểm tra chất lượng các bộ phận trước khi giao hàng không?'),
       (1, 'Bạn có thích việc xây hoặc lát gạch không?'),
       (1, 'Bạn có hứng thú với việc làm trên giàn khoan dầu ngoài biển không?'),
       (1, 'Bạn có thích lắp ráp các linh kiện điện tử không?'),
       (1, 'Bạn có thích vận hành máy mài trong nhà máy không?'),
       (1, 'Bạn có thích sửa vòi nước bị hỏng không?'),
       (1, 'Bạn có thích lắp ráp sản phẩm trong nhà máy không?'),
       (1, 'Bạn có thích lắp đặt sàn nhà cho các ngôi nhà không?'),
       (1, 'Bạn có thích tìm hiểu cấu trúc cơ thể con người không?'),
       (1, 'Bạn có hứng thú nghiên cứu hành vi động vật không?'),
       (1, 'Bạn có thích nghiên cứu về cây cối hoặc động vật không?'),
       (1, 'Bạn có muốn phát triển một phương pháp chữa bệnh mới không?'),
       (1, 'Bạn có thích làm nghiên cứu sinh học không?'),
       (1, 'Bạn có muốn tìm hiểu về cá voi và các sinh vật biển khác không?'),
       (1, 'Bạn có muốn làm việc trong phòng thí nghiệm sinh học không?'),
       (1, 'Bạn có thích lập bản đồ đáy biển không?'),
       (1, 'Bạn có thích chỉ huy một dàn nhạc hợp xướng không?'),
       (1, 'Bạn có muốn làm đạo diễn một vở kịch không?'),
       (1, 'Bạn có thích thiết kế tranh minh họa cho tạp chí không?'),
       (1, 'Bạn có thích viết nhạc, sáng tác bài hát không?'),
       (1, 'Bạn có muốn viết sách hoặc kịch bản không?'),
       (1, 'Bạn có thích chơi nhạc cụ không?'),
       (1, 'Bạn có hứng thú biểu diễn các pha mạo hiểm trong phim hoặc TV không?'),
       (1, 'Bạn có muốn thiết kế bối cảnh cho các vở kịch không?'),
       (1, 'Bạn có thích tư vấn nghề nghiệp cho người khác không?'),
       (1, 'Bạn có thích làm tình nguyện viên ở tổ chức từ thiện không?'),
       (1, 'Bạn có muốn giúp người gặp vấn đề về rượu hoặc ma túy không?'),
       (1, 'Bạn có thích dạy ai đó tập thể dục không?'),
       (1, 'Bạn có muốn giúp đỡ người gặp vấn đề gia đình không?'),
       (1, 'Bạn có thích giám sát hoạt động của trẻ em ở trại hè không?'),
       (1, 'Bạn có thích dạy trẻ em đọc sách không?'),
       (1, 'Bạn có muốn giúp người già làm việc hàng ngày không?'),
       (1, 'Bạn có thích bán nhượng quyền nhà hàng không?'),
       (1, 'Bạn có thích bán hàng trong cửa hàng bách hóa không?'),
       (1, 'Bạn có thích quản lý khách sạn không?'),
       (1, 'Bạn có muốn vận hành tiệm làm đẹp hoặc cắt tóc không?'),
       (1, 'Bạn có thích quản lý phòng ban trong công ty lớn không?'),
       (1, 'Bạn có muốn quản lý cửa hàng quần áo không?'),
       (1, 'Bạn có thích bán nhà không?'),
       (1, 'Bạn có muốn điều hành cửa hàng đồ chơi không?'),
       (1, 'Bạn có thích làm bảng lương cho văn phòng không?'),
       (1, 'Bạn có thích kiểm kê hàng hóa bằng máy tính cầm tay không?'),
       (1, 'Bạn có thích dùng máy tính để lập hóa đơn khách hàng không?'),
       (1, 'Bạn có muốn quản lý hồ sơ nhân viên không?'),
       (1, 'Bạn có thích tính toán và ghi lại dữ liệu số liệu không?'),
       (1, 'Bạn có thích dùng máy tính bỏ túi không?'),
       (1, 'Bạn có thích giúp khách hàng làm các giao dịch ngân hàng không?'),
       (1, 'Bạn có thích ghi nhận hồ sơ gửi và nhận hàng không?');

INSERT INTO Answer (question_id, content, score, trait_id)
VALUES (1, 'Không thích', 1, 1),
       (1, 'Hơi không thích', 2, 1),
       (1, 'Bình thường', 3, 1),
       (1, 'Hơi thích', 4, 1),
       (1, 'Rất thích', 5, 1),
       (2, 'Không thích', 1, 1),
       (2, 'Hơi không thích', 2, 1),
       (2, 'Bình thường', 3, 1),
       (2, 'Hơi thích', 4, 1),
       (2, 'Rất thích', 5, 1),
       (3, 'Không thích', 1, 1),
       (3, 'Hơi không thích', 2, 1),
       (3, 'Bình thường', 3, 1),
       (3, 'Hơi thích', 4, 1),
       (3, 'Rất thích', 5, 1),
       (4, 'Không thích', 1, 1),
       (4, 'Hơi không thích', 2, 1),
       (4, 'Bình thường', 3, 1),
       (4, 'Hơi thích', 4, 1),
       (4, 'Rất thích', 5, 1),
       (5, 'Không thích', 1, 1),
       (5, 'Hơi không thích', 2, 1),
       (5, 'Bình thường', 3, 1),
       (5, 'Hơi thích', 4, 1),
       (5, 'Rất thích', 5, 1),
       (6, 'Không thích', 1, 1),
       (6, 'Hơi không thích', 2, 1),
       (6, 'Bình thường', 3, 1),
       (6, 'Hơi thích', 4, 1),
       (6, 'Rất thích', 5, 1),
       (7, 'Không thích', 1, 1),
       (7, 'Hơi không thích', 2, 1),
       (7, 'Bình thường', 3, 1),
       (7, 'Hơi thích', 4, 1),
       (7, 'Rất thích', 5, 1),
       (8, 'Không thích', 1, 1),
       (8, 'Hơi không thích', 2, 1),
       (8, 'Bình thường', 3, 1),
       (8, 'Hơi thích', 4, 1),
       (8, 'Rất thích', 5, 1);


-- Thêm dữ liệu nhóm ngành
INSERT INTO majorgroup (id, code, name)
VALUES (1, 'KT', 'Kinh tế'),
       (2, 'CNTT', 'Công nghệ thông tin'),
       (3, 'SP', 'Sư phạm'),
       (4, 'YK', 'Y khoa'),
       (5, 'XD', 'Xây dựng');

-- Thêm dữ liệu ngành học
INSERT INTO major (id, code, name, major_group_id)
VALUES (1, 'KT01', 'Kinh tế quốc tế', 1),
       (2, 'KT02', 'Tài chính - Ngân hàng', 1),
       (3, 'KT03', 'Kế toán', 1),

       (4, 'IT01', 'Khoa học máy tính', 2),
       (5, 'IT02', 'Kỹ thuật phần mềm', 2),
       (6, 'IT03', 'Mạng máy tính và truyền thông dữ liệu', 2),

       (7, 'SP01', 'Sư phạm Toán học', 3),
       (8, 'SP02', 'Sư phạm Ngữ văn', 3),
       (9, 'SP03', 'Sư phạm Tiếng Anh', 3),

       (10, 'YK01', 'Y đa khoa', 4),
       (11, 'YK02', 'Răng - Hàm - Mặt', 4),
       (12, 'YK03', 'Điều dưỡng', 4),

       (13, 'XD01', 'Kỹ thuật xây dựng', 5),
       (14, 'XD02', 'Quản lý xây dựng', 5),
       (15, 'XD03', 'Công nghệ kỹ thuật vật liệu xây dựng', 5);

